on:
  push:
    branches: ['main']
  pull_request: {}

jobs:
  pr-yaml:
    permissions: write-all
    uses: DamianBis/actions-demo-lib/.github/workflows/pr.yaml@main
    with:
      repo: ${{ github.repository }}
      environment: "uat"
    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }}
